#!/usr/bin/env python3
"""Build script for the NOOR entrepreneurship course site.

1. Merges data/meta.json + data/lectures/L*.json into site/data/course.js
2. Renders one study-sheet PDF per lecture (+ a capstone template) with Chromium.

Usage:  python3 build.py [--no-pdf]
"""
import glob, html, json, os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.join(ROOT, "docs")
SRC = os.path.join(ROOT, "pdfsrc")
os.makedirs(SRC, exist_ok=True)
os.makedirs(os.path.join(SITE, "pdf"), exist_ok=True)

# ---------- 1. merge data ----------
meta = json.load(open(os.path.join(SITE, "data", "meta.json"), encoding="utf-8"))
lectures = [json.load(open(f, encoding="utf-8")) for f in sorted(glob.glob(os.path.join(SITE, "data", "lectures", "L*.json")))]
lectures.sort(key=lambda d: d["id"])
course = {
    "version": meta["version"],
    "course": meta["course"],
    "parts": meta["parts"],
    "capstone": meta["capstone"],
    "attribution": meta["attribution"],
    "lectures": lectures,
}
with open(os.path.join(SITE, "data", "course.js"), "w", encoding="utf-8") as f:
    f.write("/* Generated by build.py from meta.json and lectures/L*.json. Do not edit by hand. */\n")
    f.write("window.COURSE = " + json.dumps(course, ensure_ascii=False, indent=1) + ";\n")
print("course.js written:", len(lectures), "lectures")

if "--no-pdf" in sys.argv:
    sys.exit(0)

# ---------- 2. PDFs ----------
E = html.escape
FONT = "../docs/assets/fonts/"
CSS = """
@font-face{font-family:"Plex";font-weight:400;src:url(%(f)sibm-plex-sans-arabic-arabic-400-normal.woff2) format("woff2");unicode-range:U+0600-06FF,U+0750-077F,U+0870-088E,U+0890-0891,U+0898-08E1,U+08E3-08FF,U+200C-200E,U+2010-2011,U+204F,U+2E41,U+FB50-FDFF,U+FE70-FE74,U+FE76-FEFC}
@font-face{font-family:"Plex";font-weight:600;src:url(%(f)sibm-plex-sans-arabic-arabic-600-normal.woff2) format("woff2");unicode-range:U+0600-06FF,U+0750-077F,U+0870-088E,U+0890-0891,U+0898-08E1,U+08E3-08FF,U+200C-200E,U+2010-2011,U+204F,U+2E41,U+FB50-FDFF,U+FE70-FE74,U+FE76-FEFC}
@font-face{font-family:"Plex";font-weight:400;src:url(%(f)sibm-plex-sans-arabic-latin-400-normal.woff2) format("woff2");unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-200B,U+200F-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}
@font-face{font-family:"Plex";font-weight:600;src:url(%(f)sibm-plex-sans-arabic-latin-600-normal.woff2) format("woff2");unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-200B,U+200F-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}
@font-face{font-family:"Head";font-weight:700;src:url(%(f)samiri-arabic-700-normal.woff2) format("woff2");unicode-range:U+0600-06FF,U+0750-077F,U+200C-200E,U+2010-2011,U+FB50-FDFF,U+FE70-FE74,U+FE76-FEFC}
@font-face{font-family:"Head";font-weight:700;src:url(%(f)samiri-latin-700-normal.woff2) format("woff2");unicode-range:U+0000-00FF,U+0131,U+2000-206F,U+20AC,U+2212}
@font-face{font-family:"Cormorant";font-weight:600;src:url(%(f)scormorant-garamond-latin-600-normal.woff2) format("woff2")}
@font-face{font-family:"Cormorant";font-weight:700;src:url(%(f)scormorant-garamond-latin-700-normal.woff2) format("woff2")}
""" % {"f": FONT} + """
:root{--plum:#391D41;--plum-2:#5A3466;--plum-soft:#F1EBF4;--gold:#B9894A;--gold-deep:#8E6427;--gold-soft:#F6ECDD;--line:#DDD3E2;--text:#251B2B;--muted:#5D5066}
*{box-sizing:border-box}
html{font:400 11pt/1.8 "Plex","IBM Plex Sans Arabic",Tahoma,sans-serif;color:var(--text)}
body{margin:0}
.ltr{direction:ltr;unicode-bidi:isolate}
.top{display:flex;align-items:center;justify-content:space-between;gap:12pt;padding-bottom:8pt;border-bottom:2px solid var(--plum);margin-bottom:14pt}
.top img{height:26pt}
.top .ct{font:600 9pt "Plex";color:var(--muted);text-align:end;letter-spacing:.04em}
.kick{font:700 11pt "Cormorant",serif;letter-spacing:.14em;text-transform:uppercase;color:var(--gold-deep)}
h1{font:700 21pt/1.35 "Head","Amiri",serif;color:var(--plum);margin:2pt 0 4pt}
.en-title{direction:ltr;text-align:left;font:600 13pt/1.3 "Cormorant",serif;color:var(--muted);margin:0 0 10pt}
h2{font:700 13.5pt/1.4 "Head","Amiri",serif;color:var(--plum);margin:14pt 0 5pt;break-after:avoid}
p{margin:0 0 7pt;orphans:3;widows:3}
ul{margin:0 0 6pt;padding-inline-start:16pt}
li{margin:0 0 3pt}
.chip{display:inline-block;background:var(--gold-soft);color:var(--gold-deep);font:600 8.5pt "Plex";padding:2pt 7pt;border-radius:3pt;margin-inline-end:5pt}
.src{border:1px solid var(--line);border-radius:5pt;padding:6pt 9pt;margin-bottom:5pt;break-inside:avoid}
.src b{direction:ltr;unicode-bidi:isolate;display:inline-block}
.src .u{direction:ltr;text-align:left;font-size:8pt;color:var(--plum-2);word-break:break-all}
.src .n{font-size:9.5pt;color:var(--muted)}
.step{display:grid;grid-template-columns:24pt 1fr;gap:8pt;margin-top:10pt}
.step .sn{font:700 26pt/1 "Cormorant",serif;color:var(--gold)}
.step h2{margin-top:0}
.iraqi p{background:var(--gold-soft);padding:6pt 9pt;border-radius:4pt}
.en{direction:ltr;text-align:left}
table{width:100%;border-collapse:collapse;margin-top:4pt}
th,td{border:1px solid var(--line);padding:4pt 7pt;text-align:start;vertical-align:top;font-size:10pt}
th{background:var(--plum-soft);color:var(--plum);font:600 8.5pt "Plex";letter-spacing:.08em;text-transform:uppercase}
td:first-child{direction:ltr;text-align:left;font-weight:600;color:var(--plum)}
.act{background:var(--gold-soft);border-radius:6pt;padding:9pt 12pt;break-inside:avoid}
.act h2{margin-top:0}
.act .d{margin-top:6pt;padding-top:6pt;border-top:1px dashed #D5B98D;font-weight:600}
.q{border:1px solid var(--line);border-radius:5pt;padding:6pt 10pt;margin-bottom:6pt;break-inside:avoid}
.q .qq{font-weight:600;color:var(--plum)}
.q .aa{color:var(--muted);margin-top:2pt}
.notes{margin-top:10pt;break-inside:avoid}
.notes .ln{border-bottom:1px solid var(--line);height:17pt}
.foot{margin-top:14pt;padding-top:6pt;border-top:1px solid var(--line);font-size:8pt;line-height:1.6;color:var(--muted)}
.cap-sec{border:1px solid var(--line);border-radius:6pt;padding:8pt 12pt;margin-bottom:10pt;break-inside:avoid}
.cap-sec h3{margin:0 0 3pt;font:700 12pt "Head","Amiri",serif;color:var(--plum)}
.cap-sec .ln{border-bottom:1px solid var(--line);height:18pt}
"""

def paras(a): return "".join("<p>%s</p>" % E(x) for x in a)
def bullets(a, cls=""): return '<ul class="%s">%s</ul>' % (cls, "".join("<li>%s</li>" % E(x) for x in a))

TYPE_AR = {"video": "فيديو", "slides": "شرائح", "course": "كورس", "reading": "قراءة"}

def page(body, title):
    return """<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>%s</title><style>%s</style></head><body>%s</body></html>""" % (E(title), CSS, body)

def lecture_html(l):
    n = "%02d" % l["id"]
    part = next(p for p in meta["parts"] if p["id"] == l["part"])
    b = '<div class="top"><img src="../docs/assets/logo-web.png" alt="NOOR"><div class="ct">%s<br><span class="ltr">Noor Muhannad Ahmed</span></div></div>' % E(meta["course"]["title"]["ar"])
    b += '<div class="kick">Lecture %s · Part %d</div>' % (n, part["id"])
    b += "<h1>%s</h1>" % E(l["title"]["ar"])
    b += '<div class="en-title">%s</div>' % E(l["title"]["en"])
    b += '<span class="chip">%s · %s</span><span class="chip">ساعتان</span>' % (E(part["title"]["ar"]), E(part["title"]["en"]))
    b += "<h2>المصادر الأصلية</h2>"
    for s in l["sources"]:
        b += '<div class="src"><b>%s</b> <span class="chip">%s</span><div class="n">%s</div><div class="u">%s</div></div>' % (E(s["name"]), TYPE_AR.get(s["type"], s["type"]), E(s["note"]["ar"]), E(s["url"]))
    b += "<h2>ماذا ستتعلم</h2>" + bullets(l["objectives"]["ar"])
    b += '<div class="step"><div class="sn">1</div><div><h2>ملخص المصدر بالعربي</h2>%s</div></div>' % paras(l["summary_ar"])
    b += '<div class="step iraqi"><div class="sn">2</div><div><h2>الشرح بالعراقي</h2>%s</div></div>' % paras(l["explain_ar"])
    b += '<div class="step"><div class="sn">3</div><div class="en"><h2 style="direction:ltr">English summary (for revision)</h2>%s</div></div>' % bullets(l["summary_en"])
    b += '<div class="step"><div class="sn">4</div><div><h2>مثال تطبيقي</h2><p>%s</p><p class="en" style="color:#5D5066">%s</p></div></div>' % (E(l["example"]["ar"]), E(l["example"]["en"]))
    b += "<h2>مصطلحات المحاضرة</h2><table><thead><tr><th>Term</th><th>المعنى</th></tr></thead><tbody>%s</tbody></table>" % "".join("<tr><td>%s</td><td>%s</td></tr>" % (E(t["en"]), E(t["ar"])) for t in l["terms"])
    a = l["activity"]
    b += '<h2>&nbsp;</h2><div class="act"><h2>النشاط العملي</h2><p>%s</p><p class="en" style="color:#5D5066">%s</p><div class="d">الناتج المطلوب للمشروع الختامي: %s</div></div>' % (E(a["ar"]), E(a["en"]), E(a["deliverable"]["ar"]))
    b += "<h2>أسئلة مراجعة</h2>"
    for q in l["quiz"]:
        b += '<div class="q"><div class="qq">%s <span class="en" style="display:block;font-weight:400;color:#5D5066">%s</span></div><div class="aa">%s</div></div>' % (E(q["q"]["ar"]), E(q["q"]["en"]), E(q["a"]["ar"]))
    b += '<div class="notes"><h2>ملاحظاتي</h2>' + '<div class="ln"></div>' * 6 + "</div>"
    b += '<div class="foot">%s</div>' % E(meta["attribution"]["ar"])
    return page(b, "%s - %s" % (n, l["title"]["ar"]))

def capstone_html():
    c = meta["capstone"]
    b = '<div class="top"><img src="../docs/assets/logo-web.png" alt="NOOR"><div class="ct">%s<br><span class="ltr">Noor Muhannad Ahmed</span></div></div>' % E(meta["course"]["title"]["ar"])
    b += '<div class="kick">Capstone</div><h1>%s</h1><div class="en-title">%s</div><p>%s</p>' % (E(c["title"]["ar"]), E(c["title"]["en"]), E(c["intro"]["ar"]))
    b += "<p><b>اسم الطالب:</b> ____________________ &nbsp; <b>اسم المشروع:</b> ____________________ &nbsp; <b>التاريخ:</b> ____________</p>"
    for l in lectures:
        b += '<div class="cap-sec"><h3>%02d · %s</h3><div style="font-size:9.5pt;color:#5D5066;margin-bottom:3pt">%s</div>%s</div>' % (l["id"], E(l["title"]["ar"]), E(l["activity"]["deliverable"]["ar"]), '<div class="ln"></div>' * 4)
    b += '<h2>عرض من 7 شرائح (10 دقائق)</h2><ol><li>مقدمة وشعار جذاب</li><li>الزبون المستهدف وألمه</li><li>الحل</li><li>خطة الدخول للسوق</li><li>الأرقام المالية</li><li>الفريق والمنافسة</li><li>الخلاصة والطلب المحدد</li></ol>'
    b += "<h2>معيار التقييم المقترح</h2><table><thead><tr><th>Criterion</th><th>%s</th></tr></thead><tbody>%s</tbody></table>" % ("الدرجة", "".join("<tr><td style='direction:rtl;text-align:start;font-weight:400;color:#251B2B'>%s</td><td>%d</td></tr>" % (E(r["name"]["ar"]), r["w"]) for r in c["rubric"]))
    b += '<div class="foot">%s</div>' % E(meta["attribution"]["ar"])
    return page(b, "Capstone template")

from playwright.sync_api import sync_playwright

jobs = [("lecture-%02d" % l["id"], lecture_html(l)) for l in lectures] + [("capstone-template", capstone_html())]
FOOT = '<div style="width:100%;font-size:8px;color:#62556B;text-align:center;font-family:sans-serif"><span class="pageNumber"></span> / <span class="totalPages"></span></div>'
with sync_playwright() as p:
    br = p.chromium.launch()
    for name, doc in jobs:
        path = os.path.join(SRC, name + ".html")
        open(path, "w", encoding="utf-8").write(doc)
        pg = br.new_page()
        pg.goto("file://" + path)
        pg.wait_for_timeout(300)
        pg.evaluate("document.fonts.ready")
        out = os.path.join(SITE, "pdf", name + ".pdf")
        pg.pdf(path=out, format="A4", margin={"top": "16mm", "bottom": "16mm", "left": "15mm", "right": "15mm"}, print_background=True,
               display_header_footer=True, header_template="<span></span>", footer_template=FOOT)
        pg.close()
        print("pdf:", name, os.path.getsize(out) // 1024, "KB")
    br.close()
